on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:

      - uses: actions/setup-node@v4
        with:
          node-version: '21.1.0'

          
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.6'

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo docker run --name mycont --rm -itd --privileged -v "$(pwd):$(pwd)" -v "/Volumes:/Volumes" -w "$(pwd)" debian:experimental-20240311
          sudo docker exec --privileged -it mycont apt-get update
          sudo docker exec --privileged -it mycont apt-get install poppler-utils/experimental -y

      - uses: fawazahmed0/action-debug@main
